### ISSUE TITLE
dataset_description files. 

### ISSUE THREAD

**Issue by bpinsard** [courtois-neuromod/cneuromod#1]
I am trying to finalize dataset_descriptions jsons, we are missing a number of informations (some optional though, and we could decide these are factored in the doc) :

- License: from what I understand, we will never be able to have a standard license for the data as the "Cadre de gestion" is specific ? I would then be included in the doc, and linked in the dataset descriptions.
- Authors: who is considered an author of the dataset? Can it vary accross sub-datasets? 
- DatasetDOI: this will be set at the release
- HowToAcknowledge: to be set when the data paper is published (or preprint released) right? Or we could ask users to link to the website.

**Comment by lunebellec** [comment]
My take: 

Regarding the license, I have been trying to research that, so far without luck. The practice of data transfer agreement is quite common, but it doesn't look like there is an obvious way to pair this with a license. I guess the DTA is the license in a way, so what you suggest would make sense. 

Re the authors, for collaborative works, what I have seen done is to list the primary contributors. That would be Julie B, yourself and myself, and then add a link to a data release note. This data release note contains a summary of the release as well as a detailed list of contributions. The nilearn release notes are a really clean example https://nilearn.github.io/whats_new.html 

Re DatasetDOI, were you thinking to archive the release on zenodo?

The HowToAcknowledge paragraph is on our list of things to do for the "cadre de gestion". When there will be a data paper it will be part of the acknowledgement paragraph.
