### ISSUE TITLE
Document visual angle for video presentation/ all datasets

### ISSUE THREAD

**Issue by bpinsard** [courtois-neuromod/cneuromod#12]
We should compute values of visual angles for all movies / series (aspect ratio might vary) and document it.

**Comment by bpinsard** [comment]
@kateiyas posting it here to have a better tracking of your request. Will try to find that asap.

**Comment by seelikat** [comment]
Ok, great! Thanks.

**Comment by bpinsard** [comment]
The full screen visual angles are 17.5 horizontally and 14 vertically. All videos were maximized, so for movie10 the aspect ratio was wide, which means it was maxed horizontally (all are 12/5, except bourne which is 372:157 !?!? ) . For friends, it should be the same, as the display aspect ratio is 4/3.

**Comment by seelikat** [comment]
Thanks, this clarifies my question! 

So do I understand correctly that the heights were different depending on the movie shown? 

( I can't think of more questions right now, but will reopen the issue if something comes up. )

**Comment by bpinsard** [comment]
Yes, the height varies depending on the movie to keep the video display aspect ratio.
