### ISSUE TITLE
derivatives available?

### ISSUE THREAD

**Issue by jsmentch** [courtois-neuromod/cneuromod#15]
In the docs it says that there are fMRIprep derivatives, but these aren't listed in the readme and I don't see them within the repo. Are these available somewhere or will they be available in the future?

**Comment by arnaudbore** [comment]
Hi @jsmentch,
They will definitively be available in the near future. Still some work to be done first.

**Comment by lunebellec** [comment]
We (fairly) recently reorganized the way we generate derivatives, and the docs are not up-to-date.
I _think_ this is where derivatives currently live, and should be ready to go for the 2020 release
https://github.com/courtois-neuromod/cneuromod.fmriprep/tree/rel/2020

Unfortunately, the person who can confirm is currently on vacation, we'll confirm as soon as he's back. Sorry for the inconvenience.

**Comment by jsmentch** [comment]
Yes these do appear to be the derivatives - I am able to get them from s3 via datalad from there for now - thank you!

**Comment by bpinsard** [comment]
Hi, just back from vacations.
https://github.com/courtois-neuromod/cneuromod.processed is a super-dataset that contains all the derivatives of cneuromod.
